name: bacasaku
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  get_cli: ^1.8.4
  cupertino_icons: ^1.0.2
  get: 4.6.6
  dio: 5.4.1
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  flutter_native_splash: ^2.3.10
  carousel_slider: ^4.2.1
  curved_navigation_bar: ^1.0.3
  flutter_rating_bar: ^4.0.1
  jwt_decoder: ^2.0.1
  flutter: 
    sdk: flutter
  quickalert: ^1.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/Logo1.png
    - assets/Logo2.png
    - assets/bgimage.png
    - assets/banner_1.png
    - assets/banner_2.png
    - assets/banner_3.png
    - assets/cover_1.png
    - assets/cover_2.png
    - assets/cover_3.png
    - assets/cover_4.png
    - assets/cover_5.png
    - assets/banner_popup.jpg
    - assets/fotoprofil.png

  fonts:
      - family: Poppins
        fonts:
          - asset: assets\font\Poppins-SemiBold.ttf
            style: normal

flutter_native_splash:
  background_image: "assets/Splash.png"
  android: true
  ios: true
  web: true